//go:build !windows
// +build !windows

package main

func InitGamepad() error       { return nil }
func CloseGamepad()            {}
func Rumble(durationMs int)    {}
func IsGamepadConnected() bool { return false }

// SDL_GameController button constants used for automatic gamepad mapping.
const (
        SDL_CONTROLLER_BUTTON_A = iota
        SDL_CONTROLLER_BUTTON_B
        SDL_CONTROLLER_BUTTON_X
        SDL_CONTROLLER_BUTTON_Y
        SDL_CONTROLLER_BUTTON_BACK
        SDL_CONTROLLER_BUTTON_GUIDE
        SDL_CONTROLLER_BUTTON_START
        SDL_CONTROLLER_BUTTON_LEFTSTICK
        SDL_CONTROLLER_BUTTON_RIGHTSTICK
        SDL_CONTROLLER_BUTTON_LEFTSHOULDER
        SDL_CONTROLLER_BUTTON_RIGHTSHOULDER
        SDL_CONTROLLER_BUTTON_DPAD_UP
        SDL_CONTROLLER_BUTTON_DPAD_DOWN
        SDL_CONTROLLER_BUTTON_DPAD_LEFT
        SDL_CONTROLLER_BUTTON_DPAD_RIGHT
        SDL_CONTROLLER_BUTTON_MISC1
        SDL_CONTROLLER_BUTTON_PADDLE1
        SDL_CONTROLLER_BUTTON_PADDLE2
        SDL_CONTROLLER_BUTTON_PADDLE3
        SDL_CONTROLLER_BUTTON_PADDLE4
        SDL_CONTROLLER_BUTTON_TOUCHPAD
        SDL_CONTROLLER_BUTTON_MAX
)

// SDL_GameController axis constants used for automatic gamepad mapping.
const (
        SDL_CONTROLLER_AXIS_LEFTX = iota
        SDL_CONTROLLER_AXIS_LEFTY
        SDL_CONTROLLER_AXIS_RIGHTX
        SDL_CONTROLLER_AXIS_RIGHTY
        SDL_CONTROLLER_AXIS_TRIGGERLEFT
        SDL_CONTROLLER_AXIS_TRIGGERRIGHT
        SDL_CONTROLLER_AXIS_MAX
)
